language: go

go:
    - 1.4
    - 1.5
    - 1.6

before_script:
    - curl -O http://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf

script:
    - TESTFILE=bremen-latest.osm.pbf go test -v -race
