language: go

go:
    - 1.5
    - 1.6

before_script:
    - curl -O http://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf

script:
    - GO15VENDOREXPERIMENT=1 go build
    - GO15VENDOREXPERIMENT=1 TESTFILE=bremen-latest.osm.pbf go test -v -race

